routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => 'admin'], function() {

Route::resource('admin/users', 'Admin\AdminUsersController');
Route::get('admin/users/status/{id}', 'Admin\AdminUsersController@status') -> name('users.status');
Route::resource('admin/posts', 'Admin\AdminPostsController');
Route::resource('admin/categories', 'Admin\AdminCategoryController');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id','is_active','photo_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role() {

        return $this -> belongsTo('App\Role', 'role_id');
    }

    public function photo() {

        return $this -> belongsTo('App\Photo', 'photo_id');
    }

    public function post() {
        return $this -> hasMany('App\Post');
    }

    public function isAdmin() {

        if($this -> role_id  === 1 && $this -> is_active === 1) {

            return true;
        }
        return false;
    }


}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')
@section('main-content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
    Create User
    <small></small>
    </h1>
  </section>
  <!-- Main content -->
  <section class="content">
    <!-- Default box -->
    <div class="box">
      {{ Form::open(array('method'=>'POST','route' => 'users.store', 'files' => true)) }}
      <div class="box-body">
        <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
          {!! Form::label('name', 'Name:') !!}
          {!! Form::text('name',null, ['class' => 'form-control','placeholder'=>'Enter full name']) !!}
          @if ($errors->has('name'))
          <span class="help-block">
            <strong>{{ strtoupper($errors->first('name')) }}</strong>
          </span>
          @endif
        </div>
        <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
          {!! Form::label('email', 'Email:') !!}
          {!! Form::email('email',null, ['class' => 'form-control','placeholder'=>'Enter email address']) !!}
          @if ($errors->has('email'))
          <span class="help-block">
            <strong>{{ strtoupper($errors->first('email')) }}</strong>
          </span>
          @endif
        </div>
        <div class="form-group {{ $errors->has('role_id') ? 'has-error' : '' }}">
          {!! Form::label('role_id', 'Select Role:') !!}
          @if(isset($roles) && count($roles) > 0)
          {!! Form::select('role_id', [''=>'Choose Options'] + $roles , null, ['class'=>'form-control'])!!}
          @else
          {{ "No Roles Found" }}
          @endif
          @if ($errors->has('role_id'))
          <span class="help-block">
            <strong>{{ strtoupper($errors->first('role_id')) }}</strong>
          </span>
          @endif
        </div>
        <div class="form-group {{ $errors->has('is_active') ? 'has-error' : '' }}">
          {!! Form::label('is_active', 'Status:') !!}
          {!! Form::select('is_active', array(1 => 'Active', 0 => 'Inactive'),0, ['class' => 'form-control']) !!}
          @if ($errors->has('is_active'))
          <span class="help-block">
            <strong>{{ strtoupper($errors->first('is_active')) }}</strong>
          </span>
          @endif
        </div>
        <div class="form-group {{ $errors->has('file') ? 'has-error' : '' }}">
          {!! Form::label('photo_id', 'Image:') !!}
          {!! Form::file('photo_id',null, ['class' => 'form-control']) !!}
          @if ($errors->has('file'))
          <span class="help-block">
            <strong>{{ strtoupper($errors->first('file')) }}</strong>
          </span>
          @endif
        </div>
        <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
          {!! Form::label('password', 'Password:') !!}
          {!! Form::password('password', ['class' => 'form-control']) !!}

          @if ($errors->has('password'))
          <span class="help-block">
            <strong>{{ strtoupper($errors->first('password')) }}</strong>
          </span>
          @endif
        </div>
      </div>
      <div class="box-footer">
      {{ Form::submit('Create User',['class' => 'btn btn-primary'])}}
      </div>
   {{ Form::close() }}
  </div>
</section>
<!-- /.content -->
</div>
@endsection

@section('headSection')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('admin/dropzone/dropzone.css') }}">
<style type="text/css" media="screen">

</style>
@endsection

@section('footerSection')

<script src="{{ asset('admin/dropzone/dropzone.js') }}"></script>

@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
    Edit User
    <small></small>
    </h1>
  </section>
  <!-- Main content -->
  <section class="content">
    <!-- Default box -->
    <div class="box">

      <div class="col-sm-3" style="margin-top: 10px">
        <img src="{{ $user -> photo ? $user -> photo->file : 'https://via.placeholder.com/400'  }}" alt="" class="img-responsive img-rounded">
      </div>

      <div class="col-sm-9">
        {!! Form::model($user, ['method'=>'PATCH', 'route' => ['users.update', $user->id], 'files' => true]) !!}
        <div class="box-body">
          <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
            {!! Form::label('name', 'Name:') !!}
            {!! Form::text('name',null, ['class' => 'form-control','placeholder'=>'Enter full name']) !!}
            @if ($errors->has('name'))
            <span class="help-block">
              <strong>{{ strtoupper($errors->first('name')) }}</strong>
            </span>
            @endif
          </div>
          <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
            {!! Form::label('email', 'Email:') !!}
            {!! Form::email('email',null, ['class' => 'form-control','placeholder'=>'Enter email address']) !!}
            @if ($errors->has('email'))
            <span class="help-block">
              <strong>{{ strtoupper($errors->first('email')) }}</strong>
            </span>
            @endif
          </div>
          <div class="form-group {{ $errors->has('role_id') ? 'has-error' : '' }}">
            {!! Form::label('role_id', 'Select Role:') !!}
            @if(isset($roles) && count($roles) > 0)
            {!! Form::select('role_id', [''=>'Choose Options'] + $roles , null, ['class'=>'form-control'])!!}
            @else
            {{ "No Roles Found" }}
            @endif
            @if ($errors->has('role_id'))
            <span class="help-block">
              <strong>{{ strtoupper($errors->first('role_id')) }}</strong>
            </span>
            @endif
          </div>
          <div class="form-group {{ $errors->has('is_active') ? 'has-error' : '' }}">
            {!! Form::label('is_active', 'Status:') !!}
            {!! Form::select('is_active', array(1 => 'Active', 0 => 'Inactive'),null, ['class' => 'form-control']) !!}
            @if ($errors->has('is_active'))
            <span class="help-block">
              <strong>{{ strtoupper($errors->first('is_active')) }}</strong>
            </span>
            @endif
          </div>
          <div class="form-group {{ $errors->has('file') ? 'has-error' : '' }}">
            {!! Form::label('photo_id', 'Image:') !!}
            {!! Form::file('photo_id',null, ['class' => 'form-control']) !!}
            @if ($errors->has('file'))
            <span class="help-block">
              <strong>{{ strtoupper($errors->first('file')) }}</strong>
            </span>
            @endif
          </div>
          <div class="form-group">
          {{ Form::submit('Update User',['class' => 'btn btn-primary col-sm-2'])}}

        {{ Form::close() }}
        {{ Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $user -> id]])}}
        <div class="form-group pull-right delete">
            {{ Form::submit('Delete User',['class' => 'btn btn-danger delete'])}}
        </div>
        {{ Form::close() }}
          </div>


      </div>


    </div>
  </section>
  <!-- /.content -->
</div>
@endsection

@section('footerSection')
<script>
    $(".delete").on("submit", function(){
        return confirm("Do you want to delete this item?");
    });
</script>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')

@section('main-content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
    Users
    <small>Users Section</small>
    </h1>
  </section>
  @include('partials.messages')
  <!-- Main content -->
  <section class="content">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Data Table With Full Features</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>ID</th>
              <th>Photo</th>
              <th>Name</th>
              <th>Email</th>
              <th>Role</th>
              <th>Status</th>
              <th>Created at</th>
              <th>Updated at</th>
            </tr>
          </thead>
          <tbody>
            @if($users)
            @foreach($users as $user)
            <tr>
              <td>{{ $user->id }}</td>
              <td> <img height="50" src="{{ $user -> photo ? $user -> photo->file : 'https://via.placeholder.com/400' }}" alt=""> </td>
              <td>
                <a href="{{ route('users.edit', $user->id) }}"> {{ $user->name }} </a></td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->role ? ucfirst($user->role->name) : 'No role assigned' }}</td>
                <td> <a href="{{ route('users.status', $user -> id) }}">{{ $user->is_active === 1 ? 'Active' : 'Inactive' }}</td> </a>
                <td>{{ $user->created_at->diffForHumans() }}</td>
                <td>{{ $user->updated_at->diffForHumans() }}</td>
              </tr>
              @endforeach
              @endif

              <tfoot>
              <tr>
                <th>ID</th>
                <th>Photo</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
                <th>Created at</th>
                <th>Updated at</th>
              </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.box -->
  </section>
  <!-- /.content -->
</div>
@endsection
@section('footerSection')
<script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script>
$(function () {
$('#example1').DataTable()
({
'paging'      : true,
'lengthChange': false,
'searching'   : false,
'ordering'    : true,
'info'        : true,
'autoWidth'   : false
})
})
</script>
@endsection
@section('headSection')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
<style type="text/css" media="screen">
  .box {
    position: relative;
    border-radius: 3px;
    background: #ffffff;
    border-top: 3px solid #d2d6de;
    margin-bottom: 20px;
    margin-top: 50px;
    width: 100%;
    box-shadow: 0 1px 1px rgba(0,0,0,0.1);
}
</style>
@endsection