routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => 'admin'], function() {

Route::resource('admin/users', 'Admin\AdminUsersController');
Route::get('admin/users/status/{id}', 'Admin\AdminUsersController@status') -> name('users.status');
Route::resource('admin/posts', 'Admin\AdminPostsController');
Route::resource('admin/categories', 'Admin\AdminCategoryController');

});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'category_id', 'photo_id','title','body'
    ];

    public function user() {
    	return $this->belongsTo('App\User', 'user_id');
    }

     public function photo() {
        return $this -> belongsTo('App\Photo', 'photo_id');
    }

    public function category() {

        return $this -> belongsTo('App\Category', 'category_id');
    }

}

resources/views/admin/posts/create.blade.php
@extends('admin.layouts.app')

@section('main-content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
    Create New Post
    <small></small>
    </h1>
  </section>
  <!-- Main content -->
  <section class="content">
    <!-- Default box -->
    <div class="box">
      {{ Form::open(array('method'=>'POST','route' => 'posts.store', 'files' => true)) }}
      <div class="box-body">

        <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
          {!! Form::label('title', 'Title:') !!}
          {!! Form::text('title',null, ['class' => 'form-control','placeholder'=>'Enter full title']) !!}
          @if ($errors->has('title'))
          <span class="help-block">
            <strong>{{ strtoupper($errors->first('title')) }}</strong>
          </span>
          @endif
        </div>

        <div class="form-group {{ $errors->has('category_id') ? 'has-error' : '' }}">
          {!! Form::label('category_id', 'Category:') !!}
          @if(isset($categories) && count($categories) > 0)
          {!! Form::select('category_id', [''=>'Choose Options'] + $categories , null, ['class'=>'form-control'])!!}
          @else
          {{ "No Category Found" }}
          @endif
          @if ($errors->has('category_id'))
          <span class="help-block">
            <strong>{{ strtoupper($errors->first('category_id')) }}</strong>
          </span>
          @endif
        </div>


          <div class="form-group {{ $errors->has('body') ? 'has-error' : '' }}">
            {!! Form::label('body', 'Content:') !!}
              <div class="col-10">
                <textarea class="textarea_editor form-control" name="body" rows="15" placeholder="Content" >

                </textarea>
              </div>
                @if ($errors->has('body'))
                <span class="help-block">
                    <strong>{{ strtoupper($errors->first('body')) }}</strong>
                </span>
                @endif
        </div>


        <div class="form-group {{ $errors->has('file') ? 'has-error' : '' }}">
          {!! Form::label('photo_id', 'Image:') !!}
          {!! Form::file('photo_id',null, ['class' => 'form-control']) !!}
          @if ($errors->has('file'))
          <span class="help-block">
            <strong>{{ strtoupper($errors->first('file')) }}</strong>
          </span>
          @endif
        </div>

      </div>
      <div class="box-footer">
      {{ Form::submit('Create Post',['class' => 'btn btn-primary'])}}
      </div>
   {{ Form::close() }}

    </div>
</section>
</div>
@endsection

@section('headerSection')
<link rel="stylesheet" href="{{ asset('admin/plugins/bootstrap-wysihtml5/bbootstrap3-wysihtml5.css') }}" />
@endsection

@section('footerSection')
<script src="{{ asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.js') }}"></script>
<script>
    $(document).ready(function() {

        $('.textarea_editor').wysihtml5();


    });
</script>
@endsection

resources/views/admin/posts/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
    Create New Post
    <small></small>
    </h1>
  </section>
  <!-- Main content -->
  <section class="content">
    <!-- Default box -->
    <div class="box">
        {!! Form::model($post, ['method'=>'PATCH', 'route' => ['posts.update', $post->id], 'files' => true]) !!}
      <div class="box-body">

        <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
          {!! Form::label('title', 'Title:') !!}
          {!! Form::text('title',null, ['class' => 'form-control','placeholder'=>'Enter full title']) !!}
          @if ($errors->has('title'))
          <span class="help-block">
            <strong>{{ strtoupper($errors->first('title')) }}</strong>
          </span>
          @endif
        </div>

        <div class="form-group {{ $errors->has('category_id') ? 'has-error' : '' }}">
          {!! Form::label('category_id', 'Category:') !!}
          @if(isset($categories) && count($categories) > 0)
          {!! Form::select('category_id', [''=>'Choose Options'] + $categories , null, ['class'=>'form-control'])!!}
          @else
          {{ "No Category Found" }}
          @endif
          @if ($errors->has('category_id'))
          <span class="help-block">
            <strong>{{ strtoupper($errors->first('category_id')) }}</strong>
          </span>
          @endif
        </div>


          <div class="form-group {{ $errors->has('body') ? 'has-error' : '' }}">
            {!! Form::label('body', 'Content:') !!}
              <div class="col-10">
                <textarea class="textarea_editor form-control" name="body" rows="15" placeholder="Content" >
                {!! $post -> body !!}
                </textarea>
              </div>
                @if ($errors->has('body'))
                <span class="help-block" style="margin-left: 178px;">
                    <strong>{{ strtoupper($errors->first('body')) }}</strong>
                </span>
                @endif
        </div>


        <div class="form-group {{ $errors->has('file') ? 'has-error' : '' }}">
          {!! Form::label('photo_id', 'Image:') !!}
          {!! Form::file('photo_id',null, ['class' => 'form-control']) !!}
          @if ($errors->has('file'))
          <span class="help-block">
            <strong>{{ strtoupper($errors->first('file')) }}</strong>
          </span>
          @endif
        </div>

      </div>
      <div class="box-footer">
      {{ Form::submit('Update Post',['class' => 'btn btn-primary'])}}
      </div>
   {{ Form::close() }}

    </div>
</section>
</div>
@endsection

@section('headerSection')
<link rel="stylesheet" href="{{ asset('admin/plugins/bootstrap-wysihtml5/bbootstrap3-wysihtml5.css') }}" />
@endsection

@section('footerSection')
<script src="{{ asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.js') }}"></script>
<script>
    $(document).ready(function() {
        $('.textarea_editor').wysihtml5();
    });
</script>
@endsection

resources/views/admin/posts/index.blade.php
@extends('admin.layouts.app')

@section('main-content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
    Manage Post
    <small></small>
    </h1>
    @include('partials.messages')
  </section>
  <!-- Main content -->
  <section class="content">
    <!-- Default box -->
    <div class="box">
   <table id="example1" class="table table-bordered table-striped" cellspacing="0">
          <thead>
            <tr>
              <th>Category</th>
              <th>Photo</th>
              <th>Owner</th>
              <th>Title</th>
              <th>Body</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            @if($posts)
            @foreach($posts as $post)
            <tr>
              <td>{!! $post->category ? $post->category->name : 'No caterory' !!}</td>
              <td><img height="50" src="{{ $post -> photo ? $post -> photo -> file : 'https://via.placeholder.com/400' }}" alt=""></td>
              <td><b>{!! $post->user->name !!}<b></td>
              <td>{!! $post->title !!}</td>
              <td>{!! str_limit($post->body, 80) !!}</td>
              <td class="row" style="margin-left: 0px"><a href="{{ route('posts.edit', $post->id) }}" class="btn btn-success col-sm-6">Edit</a>

                {!! Form::open(['route' => ['posts.destroy', $post->id], 'method'=>'DELETE', 'class' => 'delete']) !!}

                {!! Form::submit('Delete', ['class' => 'btn btn-danger col-sm-6'] ) !!}

                {!! Form::close() !!}
            </td>
              </tr>
              @endforeach
              @endif

              <tfoot>
              <tr>
              <th>Category</th>
              <th>Photo</th>
              <th>Owner</th>
              <th>Title</th>
              <th>Body</th>
              <th>Action</th>
              </tr>
              </tfoot>
            </table>
    </div>
</section>
</div>
@endsection
@section('footerSection')
<script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script>
$(function () {
$('#example1').DataTable()
({
'paging'      : true,
'lengthChange': false,
'searching'   : false,
'ordering'    : true,
'info'        : true,
'autoWidth'   : false
})
})
</script>
<script>
    $(".delete").on("submit", function(){
        return confirm("Do you want to delete this item?");
    });
</script>
@endsection
@section('headSection')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
<style type="text/css" media="screen">
  .box {
    position: relative;
    border-radius: 3px;
    background: #ffffff;
    border-top: 3px solid #d2d6de;
    margin-bottom: 20px;
    margin-top: 50px;
    width: 100%;
    box-shadow: 0 1px 1px rgba(0,0,0,0.1);
}
td {
    width: 200px;
}
</style>
@endsection